### ISSUE TITLE
Discuss branching strategy

### ISSUE THREAD

**Issue by shuruev** [shuruev/Releaser#1]
This simple issue also will help me to understand how issues work :)

I'm also trying to get started with [GitHub Flavored Markdown](http://github.github.com/github-flavored-markdown/) syntax.
# Branching strategy

Questions to discuss:
- When to create a branch
- What are branch names

**Comment by shuruev** [comment]
## When to create a branch
- No commits into **master**
- Branches are created for a piece of work

Most typically, branches are related to some specific issue, but it's not required.
It could be a branch for a whole "area of features", a branch "for integration tests" or a branch "for releases".

**Comment by shuruev** [comment]
## How to name a branch

My current proposals are:
- Branches for development could be named in "author-description" style.

"Author" isn't required to be the real account name.
Just some nicknames, that we aggreed for ourselves.
E.g., `pasha` and `oleg`, or `pb` and `os` (I like the first more :)).

When branch is created for issue, it would be named as "author#issue".
When branch is created for "area of features" it would be named as "author-new-feature"

Examples:
`oleg#13`
`pasha-sending-mail`
`oleg-experiments`
`pasha#158`
- Any other branches could have no naming rules.

Examples:
`release-0.2`
`integration`

**Comment by shuruev** [comment]
Pasha, what do you think about it? :)

**Comment by pbelousov** [comment]
Yep, I agree with everything.

But I think name `release-0.2` is similar to [tags](http://learn.github.com/p/tagging.html). 

Or such name shows all commits to this branch will be delivered in version `0.2`? If so, does it mean that all code will be committed to only one branch for version?

**Comment by pbelousov** [comment]
We also could try branch strategy based on next (for example without release branches):

![Git Branching](https://confluence.oceanobservatories.org/download/attachments/22222275/Screen-shot-2009-12-24-at-11.32.03.png)

**Comment by shuruev** [comment]
`release-0.2` was just an example, and I agree that we should use tags for that.
I just wanted to mention that we could have some other branches, like `develop` at your picture, with no strict naming rules.

It seems that we've agreed on everything and I'm closing the issue for now :)

**Comment by pbelousov** [comment]
I think we have one more question.

Should we push to remote repository all branches? A lot of repositories have only branches like `develop` or `v.1.2-stable`. And in this approach it does not matter how to call local branches as far as I understand. The main thing is to understand purposes for which one or another branch is. I mean local branches could not have "author-description" style because only author will see such branches.

**Comment by shuruev** [comment]
Sounds reasonable.

Let's try to create some code at least ;)
